name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      COMMIT_SHA: ${{ github.sha }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd /var/www/
            rm -rf deploy_with_docker
            rm -rf personal_finance_manager
            git clone https://github.com/Bhavsar2106/personal_finance_manager.git
            cd personal_finance_manager
            CONTAINER_ID=$(docker ps -aqf "name=mongodb")
            if [ ! -z "$CONTAINER_ID" ]; then
              docker container stop $CONTAINER_ID
              docker container rm $CONTAINER_ID
            fi
            docker-compose -f docker-compose.prod.yml up -d --build
